"""Constants for the Pylontech H3X energy arbitrage integration."""

from homeassistant.const import Platform

DOMAIN = "h3x_predictive_dispatch"
NORDPOOL_DOMAIN = "nordpool"
PLATFORMS = [Platform.NUMBER, Platform.SELECT, Platform.SENSOR, Platform.SWITCH]

CONF_NORDPOOL_CONFIG_ENTRY = "nordpool_config_entry"
CONF_AREA = "area"
CONF_CURRENCY = "currency"
CONF_RESOLUTION = "resolution"
CONF_CONTROL_ENABLED = "control_enabled"
CONF_STRATEGY_PROFILE = "strategy_profile"
CONF_LOAD_FORECAST_MODE = "load_forecast_mode"
CONF_LOAD_HISTORY_DAYS = "load_history_days"
CONF_EV_FORECAST_MODE = "ev_forecast_mode"
CONF_EV_POWER_ENTITY = "ev_power_entity"
CONF_EV_CHARGING_THRESHOLD_W = "ev_charging_threshold_w"

CONF_EMS_MODE_ENTITY = "ems_mode_entity"
CONF_POWER_REF_ENTITY = "power_ref_entity"
CONF_SOC_ENTITY = "soc_entity"
CONF_LOAD_POWER_ENTITY = "load_power_entity"
CONF_SHELLY_TOTAL_POWER_ENTITY = "shelly_total_power_entity"
CONF_SHELLY_PHASE_A_POWER_ENTITY = "shelly_phase_a_power_entity"
CONF_SHELLY_PHASE_B_POWER_ENTITY = "shelly_phase_b_power_entity"
CONF_SHELLY_PHASE_C_POWER_ENTITY = "shelly_phase_c_power_entity"
CONF_GRID_IMPORT_POWER_ENTITY = "grid_import_power_entity"
CONF_GRID_IMPORT_AVERAGE_POWER_ENTITY = "grid_import_average_power_entity"
CONF_SOLAR_POWER_ENTITY = "solar_power_entity"
CONF_PV_ORIENTATION = "pv_orientation"
CONF_PV_PANEL_COUNT = "pv_panel_count"
CONF_PV_PANEL_WP = "pv_panel_wp"
CONF_PV_INVERTER_LIMIT_W = "pv_inverter_limit_w"
CONF_BATTERY_MODULE_COUNT_ENTITY = "battery_module_count_entity"
CONF_BATTERY_SYSTEM_CAPACITY_ENTITY = "battery_system_capacity_entity"
CONF_BATTERY_USABLE_CAPACITY_ENTITY = "battery_usable_capacity_entity"
CONF_BMS_TEMP_ENTITY = "bms_temperature_entity"
CONF_CHARGE_LIMIT_SOC_ENTITY = "charge_limit_soc_entity"
CONF_DISCHARGE_LIMIT_SOC_ENTITY = "discharge_limit_soc_entity"

CONF_BATTERY_CAPACITY_KWH = "battery_capacity_kwh"
CONF_BATTERY_USABLE_CAPACITY_KWH = "battery_usable_capacity_kwh"
CONF_BATTERY_MODULE_COUNT = "battery_module_count"
CONF_MIN_SOC = "min_soc"
CONF_MAX_SOC = "max_soc"
CONF_RESERVE_SOC = "reserve_soc"
CONF_TERMINAL_SOC_MODE = "terminal_soc_mode"
CONF_PERIODIC_FULL_CHARGE_ENABLED = "periodic_full_charge_enabled"
CONF_PERIODIC_FULL_CHARGE_INTERVAL_DAYS = "periodic_full_charge_interval_days"
CONF_PERIODIC_FULL_CHARGE_TARGET_SOC = "periodic_full_charge_target_soc"
CONF_PERIODIC_FULL_CHARGE_THRESHOLD_SOC = "periodic_full_charge_threshold_soc"
CONF_ROUND_TRIP_EFFICIENCY = "round_trip_efficiency"
CONF_CYCLE_COST = "cycle_cost_per_kwh"
CONF_MIN_PROFIT_MARGIN = "min_profit_margin_per_kwh"
CONF_BUY_COST_ADDER = "buy_cost_adder_per_kwh"
CONF_SELL_COST_ADDER = "sell_cost_adder_per_kwh"
CONF_DUTCH_TARIFF_ENABLED = "dutch_tariff_enabled"
CONF_VAT_PERCENT = "vat_percent"
CONF_ENERGY_TAX_PER_KWH = "energy_tax_per_kwh"
CONF_SUPPLIER_BUY_MARKUP = "supplier_buy_markup_per_kwh"
CONF_SUPPLIER_SELL_MARKDOWN = "supplier_sell_markdown_per_kwh"

CONF_CONTINUOUS_POWER_W = "continuous_power_w"
CONF_PEAK_POWER_W = "peak_power_w"
CONF_ENABLE_PEAK_POWER = "enable_peak_power"
CONF_PEAK_EXTRA_MARGIN = "peak_extra_margin_per_kwh"
CONF_MAX_CHARGE_C_RATE = "max_charge_c_rate"
CONF_MAX_DISCHARGE_C_RATE = "max_discharge_c_rate"
CONF_INVERTER_FULL_SCALE_POWER_W = "inverter_full_scale_power_w"
CONF_MIN_ACTIVE_POWER_W = "min_active_power_w"
CONF_GRID_IMPORT_LIMIT_W = "grid_import_limit_w"
CONF_GRID_EXPORT_LIMIT_W = "grid_export_limit_w"
CONF_DISCHARGE_POWER_MODE = "discharge_power_mode"
CONF_DISCHARGE_SPREAD_PRICE_TOLERANCE = "discharge_spread_price_tolerance"
CONF_DISCHARGE_SPREAD_MAX_HOURS = "discharge_spread_max_hours"
CONF_MIN_ACTION_DURATION_MINUTES = "min_action_duration_minutes"
CONF_ACTION_START_COST = "action_start_cost"
CONF_DIRECTION_CHANGE_COST = "direction_change_cost"
CONF_FORECAST_RISK_PERCENTILE = "forecast_risk_percentile"

CONF_HORIZON_HOURS = "horizon_hours"
CONF_UPDATE_INTERVAL_MINUTES = "update_interval_minutes"
CONF_IDLE_EMS_MODE = "idle_ems_mode"
CONF_USER_EMS_MODE = "user_ems_mode"
CONF_MIN_CHARGE_TEMP_C = "min_charge_temperature_c"
CONF_MAX_BMS_TEMP_C = "max_bms_temperature_c"

DEFAULT_NORDPOOL_ENTRY = "auto"
DEFAULT_AREA = "auto"
DEFAULT_CURRENCY = "auto"
DEFAULT_RESOLUTION = 15
DEFAULT_STRATEGY_PROFILE = "typical"
DEFAULT_LOAD_FORECAST_MODE = "historical"
DEFAULT_EV_FORECAST_MODE = "detect"

DEFAULT_EMS_MODE_ENTITY = "select.pylontech_h3x_bridge_ems_mode"
DEFAULT_POWER_REF_ENTITY = "number.pylontech_h3x_bridge_charge_discharge_power_ref"
DEFAULT_SOC_ENTITY = "sensor.pylontech_h3x_bridge_battery_soc"
DEFAULT_LOAD_POWER_ENTITY = "sensor.pylontech_h3x_bridge_load_power"
DEFAULT_SHELLY_TOTAL_POWER_ENTITY = ""
DEFAULT_SHELLY_PHASE_A_POWER_ENTITY = ""
DEFAULT_SHELLY_PHASE_B_POWER_ENTITY = ""
DEFAULT_SHELLY_PHASE_C_POWER_ENTITY = ""
DEFAULT_GRID_IMPORT_POWER_ENTITY = "sensor.dsmr_reading_electricity_currently_delivered"
DEFAULT_GRID_IMPORT_AVERAGE_POWER_ENTITY = (
    "sensor.connect_energy_meter_electricity_average"
)
DEFAULT_SOLAR_POWER_ENTITY = ""
DEFAULT_PV_ORIENTATION = "S"
DEFAULT_PV_PANEL_COUNT = 0.0
DEFAULT_PV_PANEL_WP = 400.0
DEFAULT_PV_INVERTER_LIMIT_W = 2000.0
DEFAULT_BATTERY_MODULE_COUNT_ENTITY = (
    "sensor.pylontech_h3x_bridge_battery_module_count"
)
DEFAULT_BATTERY_SYSTEM_CAPACITY_ENTITY = (
    "sensor.pylontech_h3x_bridge_battery_system_capacity"
)
DEFAULT_BATTERY_USABLE_CAPACITY_ENTITY = (
    "sensor.pylontech_h3x_bridge_battery_usable_capacity"
)
DEFAULT_BMS_TEMP_ENTITY = "sensor.pylontech_h3x_bridge_bms_temperature"
DEFAULT_CHARGE_LIMIT_SOC_ENTITY = "number.pylontech_h3x_bridge_charge_limit_soc"
DEFAULT_DISCHARGE_LIMIT_SOC_ENTITY = (
    "number.pylontech_h3x_bridge_discharge_limit_soc_eps"
)

DEFAULTS = {
    CONF_NORDPOOL_CONFIG_ENTRY: DEFAULT_NORDPOOL_ENTRY,
    CONF_AREA: DEFAULT_AREA,
    CONF_CURRENCY: DEFAULT_CURRENCY,
    CONF_RESOLUTION: DEFAULT_RESOLUTION,
    CONF_CONTROL_ENABLED: False,
    CONF_STRATEGY_PROFILE: DEFAULT_STRATEGY_PROFILE,
    CONF_LOAD_FORECAST_MODE: DEFAULT_LOAD_FORECAST_MODE,
    CONF_LOAD_HISTORY_DAYS: 28.0,
    CONF_EV_FORECAST_MODE: DEFAULT_EV_FORECAST_MODE,
    CONF_EV_POWER_ENTITY: "",
    CONF_EV_CHARGING_THRESHOLD_W: 2800.0,
    CONF_EMS_MODE_ENTITY: DEFAULT_EMS_MODE_ENTITY,
    CONF_POWER_REF_ENTITY: DEFAULT_POWER_REF_ENTITY,
    CONF_SOC_ENTITY: DEFAULT_SOC_ENTITY,
    CONF_LOAD_POWER_ENTITY: DEFAULT_LOAD_POWER_ENTITY,
    CONF_SHELLY_TOTAL_POWER_ENTITY: DEFAULT_SHELLY_TOTAL_POWER_ENTITY,
    CONF_SHELLY_PHASE_A_POWER_ENTITY: DEFAULT_SHELLY_PHASE_A_POWER_ENTITY,
    CONF_SHELLY_PHASE_B_POWER_ENTITY: DEFAULT_SHELLY_PHASE_B_POWER_ENTITY,
    CONF_SHELLY_PHASE_C_POWER_ENTITY: DEFAULT_SHELLY_PHASE_C_POWER_ENTITY,
    CONF_GRID_IMPORT_POWER_ENTITY: DEFAULT_GRID_IMPORT_POWER_ENTITY,
    CONF_GRID_IMPORT_AVERAGE_POWER_ENTITY: DEFAULT_GRID_IMPORT_AVERAGE_POWER_ENTITY,
    CONF_SOLAR_POWER_ENTITY: DEFAULT_SOLAR_POWER_ENTITY,
    CONF_PV_ORIENTATION: DEFAULT_PV_ORIENTATION,
    CONF_PV_PANEL_COUNT: DEFAULT_PV_PANEL_COUNT,
    CONF_PV_PANEL_WP: DEFAULT_PV_PANEL_WP,
    CONF_PV_INVERTER_LIMIT_W: DEFAULT_PV_INVERTER_LIMIT_W,
    CONF_BATTERY_MODULE_COUNT_ENTITY: DEFAULT_BATTERY_MODULE_COUNT_ENTITY,
    CONF_BATTERY_SYSTEM_CAPACITY_ENTITY: DEFAULT_BATTERY_SYSTEM_CAPACITY_ENTITY,
    CONF_BATTERY_USABLE_CAPACITY_ENTITY: DEFAULT_BATTERY_USABLE_CAPACITY_ENTITY,
    CONF_BMS_TEMP_ENTITY: DEFAULT_BMS_TEMP_ENTITY,
    CONF_CHARGE_LIMIT_SOC_ENTITY: DEFAULT_CHARGE_LIMIT_SOC_ENTITY,
    CONF_DISCHARGE_LIMIT_SOC_ENTITY: DEFAULT_DISCHARGE_LIMIT_SOC_ENTITY,
    CONF_BATTERY_MODULE_COUNT: 6.0,
    CONF_BATTERY_CAPACITY_KWH: 30.72,
    CONF_BATTERY_USABLE_CAPACITY_KWH: 29.17,
    CONF_MIN_SOC: 15.0,
    CONF_MAX_SOC: 90.0,
    CONF_RESERVE_SOC: 20.0,
    CONF_TERMINAL_SOC_MODE: "preserve_current",
    CONF_PERIODIC_FULL_CHARGE_ENABLED: True,
    CONF_PERIODIC_FULL_CHARGE_INTERVAL_DAYS: 7.0,
    CONF_PERIODIC_FULL_CHARGE_TARGET_SOC: 100.0,
    CONF_PERIODIC_FULL_CHARGE_THRESHOLD_SOC: 99.0,
    CONF_ROUND_TRIP_EFFICIENCY: 0.90,
    CONF_CYCLE_COST: 0.035,
    CONF_MIN_PROFIT_MARGIN: 0.015,
    CONF_BUY_COST_ADDER: 0.0,
    CONF_SELL_COST_ADDER: 0.0,
    # 2026 Dutch first-band electricity tax, excluding VAT. The fixed annual
    # tax rebate is intentionally excluded because dispatch cannot change it.
    CONF_DUTCH_TARIFF_ENABLED: True,
    CONF_VAT_PERCENT: 21.0,
    CONF_ENERGY_TAX_PER_KWH: 0.09161,
    CONF_SUPPLIER_BUY_MARKUP: 0.02,
    CONF_SUPPLIER_SELL_MARKDOWN: 0.0,
    CONF_CONTINUOUS_POWER_W: 11000.0,
    CONF_PEAK_POWER_W: 13800.0,
    CONF_ENABLE_PEAK_POWER: True,
    CONF_PEAK_EXTRA_MARGIN: 0.05,
    CONF_MAX_CHARGE_C_RATE: 0.5,
    CONF_MAX_DISCHARGE_C_RATE: 0.45,
    CONF_INVERTER_FULL_SCALE_POWER_W: 13800.0,
    CONF_MIN_ACTIVE_POWER_W: 500.0,
    CONF_GRID_IMPORT_LIMIT_W: 17500.0,
    CONF_GRID_EXPORT_LIMIT_W: 0.0,
    CONF_DISCHARGE_POWER_MODE: "spread",
    CONF_DISCHARGE_SPREAD_PRICE_TOLERANCE: 10.0,
    CONF_DISCHARGE_SPREAD_MAX_HOURS: 3.0,
    CONF_MIN_ACTION_DURATION_MINUTES: 30.0,
    CONF_ACTION_START_COST: 0.035,
    CONF_DIRECTION_CHANGE_COST: 0.08,
    CONF_FORECAST_RISK_PERCENTILE: 70.0,
    CONF_HORIZON_HOURS: 36.0,
    CONF_UPDATE_INTERVAL_MINUTES: 5.0,
    CONF_IDLE_EMS_MODE: "Self-Consumption",
    CONF_USER_EMS_MODE: "User mode",
    CONF_MIN_CHARGE_TEMP_C: 5.0,
    CONF_MAX_BMS_TEMP_C: 45.0,
}

NORDPOOL_AREAS = (
    "auto",
    "EE",
    "LT",
    "LV",
    "AT",
    "BE",
    "FR",
    "GER",
    "NL",
    "PL",
    "DK1",
    "DK2",
    "FI",
    "NO1",
    "NO2",
    "NO3",
    "NO4",
    "NO5",
    "SE1",
    "SE2",
    "SE3",
    "SE4",
    "SYS",
)

CURRENCIES = ("auto", "DKK", "EUR", "NOK", "PLN", "SEK")
RESOLUTIONS = (15, 30, 60)
TERMINAL_SOC_MODES = ("preserve_current", "reserve_only")
DISCHARGE_POWER_MODES = ("spread", "max_economic")
LOAD_FORECAST_MODES = ("historical", "live_flat")
EV_FORECAST_MODES = ("off", "detect", "sensor")
PV_ORIENTATIONS = ("N", "NE", "E", "SE", "S", "SW", "W", "NW")
FORCE_H3_MODULE_CAPACITY_KWH = 5.12
FORCE_H3_USABLE_DOD = 0.95
FORCE_H3_SYSTEM_CAPACITY_KWH = {
    2: 10.24,
    3: 15.36,
    4: 20.48,
    5: 25.60,
    6: 30.72,
    7: 35.84,
}
FORCE_H3_USABLE_CAPACITY_KWH = {
    2: 9.69,
    3: 14.73,
    4: 19.48,
    5: 24.32,
    6: 29.17,
    7: 34.01,
}
FORCE_H3_MIN_MODULES = 2
FORCE_H3_MAX_MODULES = 7
STRATEGY_PROFILES = ("conservative", "typical", "spread", "aggressive", "custom")
STRATEGY_PROFILE_SETTINGS = {
    "conservative": {
        CONF_TERMINAL_SOC_MODE: "preserve_current",
        CONF_PERIODIC_FULL_CHARGE_ENABLED: True,
        CONF_DISCHARGE_POWER_MODE: "spread",
        CONF_DISCHARGE_SPREAD_PRICE_TOLERANCE: 20.0,
        CONF_DISCHARGE_SPREAD_MAX_HOURS: 4.0,
        CONF_MIN_SOC: 20.0,
        CONF_MAX_SOC: 85.0,
        CONF_RESERVE_SOC: 25.0,
        CONF_MIN_PROFIT_MARGIN: 0.03,
        CONF_ENABLE_PEAK_POWER: False,
        CONF_MAX_CHARGE_C_RATE: 0.35,
        CONF_MAX_DISCHARGE_C_RATE: 0.35,
        CONF_MIN_ACTION_DURATION_MINUTES: 60.0,
        CONF_ACTION_START_COST: 0.06,
        CONF_DIRECTION_CHANGE_COST: 0.14,
        CONF_FORECAST_RISK_PERCENTILE: 85.0,
    },
    "typical": {
        CONF_TERMINAL_SOC_MODE: "preserve_current",
        CONF_PERIODIC_FULL_CHARGE_ENABLED: True,
        CONF_DISCHARGE_POWER_MODE: "spread",
        CONF_DISCHARGE_SPREAD_PRICE_TOLERANCE: 10.0,
        CONF_DISCHARGE_SPREAD_MAX_HOURS: 3.0,
        CONF_MIN_SOC: 15.0,
        CONF_MAX_SOC: 90.0,
        CONF_RESERVE_SOC: 20.0,
        CONF_MIN_PROFIT_MARGIN: 0.015,
        CONF_ENABLE_PEAK_POWER: True,
        CONF_MAX_CHARGE_C_RATE: 0.5,
        CONF_MAX_DISCHARGE_C_RATE: 0.45,
        CONF_MIN_ACTION_DURATION_MINUTES: 30.0,
        CONF_ACTION_START_COST: 0.035,
        CONF_DIRECTION_CHANGE_COST: 0.08,
        CONF_FORECAST_RISK_PERCENTILE: 70.0,
    },
    "spread": {
        CONF_TERMINAL_SOC_MODE: "preserve_current",
        CONF_PERIODIC_FULL_CHARGE_ENABLED: True,
        CONF_DISCHARGE_POWER_MODE: "spread",
        CONF_DISCHARGE_SPREAD_PRICE_TOLERANCE: 18.0,
        CONF_DISCHARGE_SPREAD_MAX_HOURS: 5.0,
        CONF_MIN_SOC: 15.0,
        CONF_MAX_SOC: 90.0,
        CONF_RESERVE_SOC: 20.0,
        CONF_MIN_PROFIT_MARGIN: 0.012,
        CONF_ENABLE_PEAK_POWER: False,
        CONF_MAX_CHARGE_C_RATE: 0.4,
        CONF_MAX_DISCHARGE_C_RATE: 0.3,
        CONF_MIN_ACTION_DURATION_MINUTES: 45.0,
        CONF_ACTION_START_COST: 0.045,
        CONF_DIRECTION_CHANGE_COST: 0.1,
        CONF_FORECAST_RISK_PERCENTILE: 70.0,
    },
    "aggressive": {
        CONF_TERMINAL_SOC_MODE: "reserve_only",
        CONF_PERIODIC_FULL_CHARGE_ENABLED: False,
        CONF_DISCHARGE_POWER_MODE: "max_economic",
        CONF_MIN_SOC: 15.0,
        CONF_MAX_SOC: 100.0,
        CONF_RESERVE_SOC: 15.0,
        CONF_MIN_PROFIT_MARGIN: 0.0,
        CONF_ENABLE_PEAK_POWER: True,
        CONF_MAX_CHARGE_C_RATE: 0.5,
        CONF_MAX_DISCHARGE_C_RATE: 0.5,
        CONF_MIN_ACTION_DURATION_MINUTES: 15.0,
        CONF_ACTION_START_COST: 0.01,
        CONF_DIRECTION_CHANGE_COST: 0.025,
        CONF_FORECAST_RISK_PERCENTILE: 55.0,
    },
}

NORDPOOL_CONF_AREAS = "areas"
NORDPOOL_CONF_CURRENCY = "currency"
